<?php

declare(strict_types=1);

namespace RefRing\MoneroRpcPhp\WalletRpc;

use RefRing\MoneroRpcPhp\Model\Address;
use RefRing\MoneroRpcPhp\Request\ParameterInterface;
use RefRing\MoneroRpcPhp\Request\RpcRequest;
use Square\Pjson\Json;
use Square\Pjson\JsonSerialize;

/**
 * Verify a signature on a string.
 */
class VerifyRequest implements ParameterInterface
{
    use JsonSerialize;

    /**
     * What should have been signed.
     */
    #[Json]
    public string $data;

    /**
     * Public address of the wallet used to `sign` the data.
     */
    #[Json]
    public Address $address;

    /**
     * signature generated by `sign` method.
     */
    #[Json]
    public string $signature;


    public static function create(string $data, Address $address, string $signature): RpcRequest
    {
        $self = new self();
        $self->data = $data;
        $self->address = $address;
        $self->signature = $signature;
        return new RpcRequest('verify', $self);
    }
}
